// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
    public static void main(String[]  args) {
        // Replace this comment with your code
        
        int N = Integer.parseInt(args[0]);

        int countgreater = 0;
        int countlessorequal = 0;
        

        for (int i = 0; i < N; i++) {
            double X = Math.random();

            if (X > 0.5) {
                countgreater++;
            } else {
                countlessorequal++;
            }
        }
        System.out.println("> 0.5: " + countgreater + " times");
        System.out.println("<= 0.5: " + countlessorequal + " times");
        
        if (countlessorequal != 0) {
            double ratio = (double) countgreater / countlessorequal;
            System.out.println("Ratio: " + ratio);
        }
        

    }
}
